version: '3'
services:
    lord_webadm:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./../dist:/var/www/html/public"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_HOST=localhost
        container_name: lord_webadm

        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - lord_mysqldb
        networks:
             - lord
    composer:
        image: "composer"
        volumes:
            - "./web/app:/app"
        command: install
        networks:
             - lord

    lord_myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: lord_phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=lord_mysqldb
        restart: always
        depends_on:
            - lord_mysqldb
        networks:
             - lord

    lord_mysqldb:
        image: mysql:latest
        container_name: lord_mysqldb
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=shelldb
            - MYSQL_ROOT_PASSWORD=meteor
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=meteor
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
        networks:
             - lord
networks:
   lord:
      driver: bridge
